//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente_AdoptMe.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cliente_AdoptMe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar ubicación.
        /// </summary>
        public static string btn_ActualizarUbicacion {
            get {
                return ResourceManager.GetString("btn_ActualizarUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string btn_CerrarSesion {
            get {
                return ResourceManager.GetString("btn_CerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar.
        /// </summary>
        public static string btn_Consultar {
            get {
                return ResourceManager.GetString("btn_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar.
        /// </summary>
        public static string btn_Descargar {
            get {
                return ResourceManager.GetString("btn_Descargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string btn_Eliminar {
            get {
                return ResourceManager.GetString("btn_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar mensaje.
        /// </summary>
        public static string btn_EnviarMensaje {
            get {
                return ResourceManager.GetString("btn_EnviarMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar reportes.
        /// </summary>
        public static string btn_GenerarReportes {
            get {
                return ResourceManager.GetString("btn_GenerarReportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string btn_IniciarSesion {
            get {
                return ResourceManager.GetString("btn_IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú Principal.
        /// </summary>
        public static string btn_MenuPrincipal {
            get {
                return ResourceManager.GetString("btn_MenuPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtener ubicación.
        /// </summary>
        public static string btn_ObtenerUbicacion {
            get {
                return ResourceManager.GetString("btn_ObtenerUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        public static string btn_Registrar {
            get {
                return ResourceManager.GetString("btn_Registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar adopción.
        /// </summary>
        public static string btn_RegistrarAdopcion {
            get {
                return ResourceManager.GetString("btn_RegistrarAdopcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar ubicación.
        /// </summary>
        public static string btn_RegistrarUbicacion {
            get {
                return ResourceManager.GetString("btn_RegistrarUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REGISTRATE.
        /// </summary>
        public static string btn_Registrate {
            get {
                return ResourceManager.GetString("btn_Registrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitar.
        /// </summary>
        public static string btn_Solicitar {
            get {
                return ResourceManager.GetString("btn_Solicitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitudes pendientes.
        /// </summary>
        public static string btn_SolicitudesPendientes {
            get {
                return ResourceManager.GetString("btn_SolicitudesPendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir foto.
        /// </summary>
        public static string btn_SubirFoto {
            get {
                return ResourceManager.GetString("btn_SubirFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir video.
        /// </summary>
        public static string btn_SubirVideo {
            get {
                return ResourceManager.GetString("btn_SubirVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver adopciones.
        /// </summary>
        public static string btn_VerAdopciones {
            get {
                return ResourceManager.GetString("btn_VerAdopciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver detalles.
        /// </summary>
        public static string btn_VerDetalles {
            get {
                return ResourceManager.GetString("btn_VerDetalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver video.
        /// </summary>
        public static string btn_VerVideo {
            get {
                return ResourceManager.GetString("btn_VerVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ❌ Cerrar.
        /// </summary>
        public static string btn_Video_Cerrar {
            get {
                return ResourceManager.GetString("btn_Video_Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ⏹ Detener.
        /// </summary>
        public static string btn_Video_Detener {
            get {
                return ResourceManager.GetString("btn_Video_Detener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ⏸ Pausar.
        /// </summary>
        public static string btn_Video_Pausar {
            get {
                return ResourceManager.GetString("btn_Video_Pausar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ▶ Reproducir.
        /// </summary>
        public static string btn_Video_Reproducir {
            get {
                return ResourceManager.GetString("btn_Video_Reproducir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string global_Aceptar {
            get {
                return ResourceManager.GetString("global_Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año.
        /// </summary>
        public static string global_Anio {
            get {
                return ResourceManager.GetString("global_Anio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string global_Cancelar {
            get {
                return ResourceManager.GetString("global_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string global_Cerrar {
            get {
                return ResourceManager.GetString("global_Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad.
        /// </summary>
        public static string global_Ciudad {
            get {
                return ResourceManager.GetString("global_Ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string global_ConfirmarContrasena {
            get {
                return ResourceManager.GetString("global_ConfirmarContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string global_Contrasena {
            get {
                return ResourceManager.GetString("global_Contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string global_Correo {
            get {
                return ResourceManager.GetString("global_Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string global_Descripcion {
            get {
                return ResourceManager.GetString("global_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edad.
        /// </summary>
        public static string global_Edad {
            get {
                return ResourceManager.GetString("global_Edad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string global_Error {
            get {
                return ResourceManager.GetString("global_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error con la base de datos.
        /// </summary>
        public static string global_ErrorBD {
            get {
                return ResourceManager.GetString("global_ErrorBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error con el servidor.
        /// </summary>
        public static string global_ErrorServidor {
            get {
                return ResourceManager.GetString("global_ErrorServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La solicitud tardó demasiado en responder.
        /// </summary>
        public static string global_ErrorTiempo {
            get {
                return ResourceManager.GetString("global_ErrorTiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Especie.
        /// </summary>
        public static string global_Especie {
            get {
                return ResourceManager.GetString("global_Especie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string global_Estado {
            get {
                return ResourceManager.GetString("global_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatura.
        /// </summary>
        public static string global_Estatura {
            get {
                return ResourceManager.GetString("global_Estatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Éxito.
        /// </summary>
        public static string global_Exito {
            get {
                return ResourceManager.GetString("global_Exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string global_Guardar {
            get {
                return ResourceManager.GetString("global_Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensajes.
        /// </summary>
        public static string global_Mensajes {
            get {
                return ResourceManager.GetString("global_Mensajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mes.
        /// </summary>
        public static string global_Mes {
            get {
                return ResourceManager.GetString("global_Mes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string global_Nombre {
            get {
                return ResourceManager.GetString("global_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Raza.
        /// </summary>
        public static string global_Raza {
            get {
                return ResourceManager.GetString("global_Raza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sexo.
        /// </summary>
        public static string global_Sexo {
            get {
                return ResourceManager.GetString("global_Sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño.
        /// </summary>
        public static string global_Tamano {
            get {
                return ResourceManager.GetString("global_Tamano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        public static string global_Telefono {
            get {
                return ResourceManager.GetString("global_Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string global_Usuario {
            get {
                return ResourceManager.GetString("global_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario y/o contraseña son incorrectos, favor de verificar..
        /// </summary>
        public static string mensaje_CredencialesIncorrectas {
            get {
                return ResourceManager.GetString("mensaje_CredencialesIncorrectas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexión con la base de datos.
        /// </summary>
        public static string mensaje_ErrorBD {
            get {
                return ResourceManager.GetString("mensaje_ErrorBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error inesperado.
        /// </summary>
        public static string mensaje_ErrorGeneral {
            get {
                return ResourceManager.GetString("mensaje_ErrorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexión con el servidor.
        /// </summary>
        public static string mensaje_ErrorServidor {
            get {
                return ResourceManager.GetString("mensaje_ErrorServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al obtener la ubicación, favor de intentarlo más tarde..
        /// </summary>
        public static string mensaje_ErrorUbicacion {
            get {
                return ResourceManager.GetString("mensaje_ErrorUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceso denegado.
        /// </summary>
        public static string mensaje_NoAutenticado {
            get {
                return ResourceManager.GetString("mensaje_NoAutenticado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil actualizado correctamente.
        /// </summary>
        public static string mensaje_PerfilActualizado {
            get {
                return ResourceManager.GetString("mensaje_PerfilActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea permitir que obtengamos su ubicación?.
        /// </summary>
        public static string mensaje_PermitirUbicacion {
            get {
                return ResourceManager.GetString("mensaje_PermitirUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud enviada correctamente.
        /// </summary>
        public static string mensaje_SolicitudEnviada {
            get {
                return ResourceManager.GetString("mensaje_SolicitudEnviada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar modificación.
        /// </summary>
        public static string titulo_ConfirmarModificacion {
            get {
                return ResourceManager.GetString("titulo_ConfirmarModificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credenciales incorrectas.
        /// </summary>
        public static string titulo_CredencialesIncorrectas {
            get {
                return ResourceManager.GetString("titulo_CredencialesIncorrectas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permisos ubicación.
        /// </summary>
        public static string titulo_PermisosUbicacion {
            get {
                return ResourceManager.GetString("titulo_PermisosUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adopciones registradas.
        /// </summary>
        public static string txtbl_AdopcionesRegistradas {
            get {
                return ResourceManager.GetString("txtbl_AdopcionesRegistradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido:.
        /// </summary>
        public static string txtbl_Bienvenido {
            get {
                return ResourceManager.GetString("txtbl_Bienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar adopciones.
        /// </summary>
        public static string txtbl_BuscarAdopciones {
            get {
                return ResourceManager.GetString("txtbl_BuscarAdopciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo vacio o incorrecto.
        /// </summary>
        public static string txtbl_CampoVacioIncorrecto {
            get {
                return ResourceManager.GetString("txtbl_CampoVacioIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Envía un mensaje.
        /// </summary>
        public static string txtbl_EnviaUnMensaje {
            get {
                return ResourceManager.GetString("txtbl_EnviaUnMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información de la mascota.
        /// </summary>
        public static string txtbl_InformacionMascota {
            get {
                return ResourceManager.GetString("txtbl_InformacionMascota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información del usuario.
        /// </summary>
        public static string txtbl_InformacionUsuario {
            get {
                return ResourceManager.GetString("txtbl_InformacionUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de sesión.
        /// </summary>
        public static string txtbl_InicioSesion {
            get {
                return ResourceManager.GetString("txtbl_InicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar campo.
        /// </summary>
        public static string txtbl_ModificarCampo {
            get {
                return ResourceManager.GetString("txtbl_ModificarCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de la mascota.
        /// </summary>
        public static string txtbl_NombreMascota {
            get {
                return ResourceManager.GetString("txtbl_NombreMascota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo valor.
        /// </summary>
        public static string txtbl_NuevoValor {
            get {
                return ResourceManager.GetString("txtbl_NuevoValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opcional.
        /// </summary>
        public static string txtbl_Opcional {
            get {
                return ResourceManager.GetString("txtbl_Opcional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Previsualización reporte.
        /// </summary>
        public static string txtbl_PrevisualizacionReporte {
            get {
                return ResourceManager.GetString("txtbl_PrevisualizacionReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar adopción.
        /// </summary>
        public static string txtbl_RegistrarAdopcion {
            get {
                return ResourceManager.GetString("txtbl_RegistrarAdopcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        public static string txtbl_Registro {
            get {
                return ResourceManager.GetString("txtbl_Registro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte de mascotas adoptadas.
        /// </summary>
        public static string txtbl_ReporteMascotasAdoptadas {
            get {
                return ResourceManager.GetString("txtbl_ReporteMascotasAdoptadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte de mascotas en adopción.
        /// </summary>
        public static string txtbl_ReporteMascotasEnAdopcion {
            get {
                return ResourceManager.GetString("txtbl_ReporteMascotasEnAdopcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro qué deseas modificar la ubicación?.
        /// </summary>
        public static string txtbl_SeguroDeModificarUbicacion {
            get {
                return ResourceManager.GetString("txtbl_SeguroDeModificarUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La ubicación no es precisa, por favor, seleccione su ubicación dando doble clic de ser necesario..
        /// </summary>
        public static string txtbl_UbicacionImprecisa {
            get {
                return ResourceManager.GetString("txtbl_UbicacionImprecisa", resourceCulture);
            }
        }
    }
}
