// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Grpc/Protos/chat.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace ChatGrpc {
  public static partial class ServicioChat
  {
    static readonly string __ServiceName = "chat.ServicioChat";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ChatGrpc.MensajeChat> __Marshaller_chat_MensajeChat = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ChatGrpc.MensajeChat.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ChatGrpc.Empty> __Marshaller_chat_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ChatGrpc.Empty.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ChatGrpc.SolicitudMensajes> __Marshaller_chat_SolicitudMensajes = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ChatGrpc.SolicitudMensajes.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ChatGrpc.RespuestaMensajes> __Marshaller_chat_RespuestaMensajes = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ChatGrpc.RespuestaMensajes.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ChatGrpc.SolicitudObtenerContactos> __Marshaller_chat_SolicitudObtenerContactos = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ChatGrpc.SolicitudObtenerContactos.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ChatGrpc.RespuestaContactos> __Marshaller_chat_RespuestaContactos = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ChatGrpc.RespuestaContactos.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::ChatGrpc.MensajeChat, global::ChatGrpc.Empty> __Method_PublicarMensaje = new grpc::Method<global::ChatGrpc.MensajeChat, global::ChatGrpc.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "PublicarMensaje",
        __Marshaller_chat_MensajeChat,
        __Marshaller_chat_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::ChatGrpc.Empty, global::ChatGrpc.MensajeChat> __Method_SuscribirMensajes = new grpc::Method<global::ChatGrpc.Empty, global::ChatGrpc.MensajeChat>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "SuscribirMensajes",
        __Marshaller_chat_Empty,
        __Marshaller_chat_MensajeChat);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::ChatGrpc.SolicitudMensajes, global::ChatGrpc.RespuestaMensajes> __Method_ObtenerMensajes = new grpc::Method<global::ChatGrpc.SolicitudMensajes, global::ChatGrpc.RespuestaMensajes>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ObtenerMensajes",
        __Marshaller_chat_SolicitudMensajes,
        __Marshaller_chat_RespuestaMensajes);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::ChatGrpc.SolicitudObtenerContactos, global::ChatGrpc.RespuestaContactos> __Method_ObtenerContactos = new grpc::Method<global::ChatGrpc.SolicitudObtenerContactos, global::ChatGrpc.RespuestaContactos>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ObtenerContactos",
        __Marshaller_chat_SolicitudObtenerContactos,
        __Marshaller_chat_RespuestaContactos);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::ChatGrpc.ChatReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for ServicioChat</summary>
    public partial class ServicioChatClient : grpc::ClientBase<ServicioChatClient>
    {
      /// <summary>Creates a new client for ServicioChat</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ServicioChatClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ServicioChat that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ServicioChatClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ServicioChatClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ServicioChatClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::ChatGrpc.Empty PublicarMensaje(global::ChatGrpc.MensajeChat request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PublicarMensaje(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::ChatGrpc.Empty PublicarMensaje(global::ChatGrpc.MensajeChat request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_PublicarMensaje, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::ChatGrpc.Empty> PublicarMensajeAsync(global::ChatGrpc.MensajeChat request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PublicarMensajeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::ChatGrpc.Empty> PublicarMensajeAsync(global::ChatGrpc.MensajeChat request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_PublicarMensaje, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::ChatGrpc.MensajeChat> SuscribirMensajes(global::ChatGrpc.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SuscribirMensajes(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::ChatGrpc.MensajeChat> SuscribirMensajes(global::ChatGrpc.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_SuscribirMensajes, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::ChatGrpc.RespuestaMensajes ObtenerMensajes(global::ChatGrpc.SolicitudMensajes request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ObtenerMensajes(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::ChatGrpc.RespuestaMensajes ObtenerMensajes(global::ChatGrpc.SolicitudMensajes request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ObtenerMensajes, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::ChatGrpc.RespuestaMensajes> ObtenerMensajesAsync(global::ChatGrpc.SolicitudMensajes request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ObtenerMensajesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::ChatGrpc.RespuestaMensajes> ObtenerMensajesAsync(global::ChatGrpc.SolicitudMensajes request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ObtenerMensajes, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::ChatGrpc.RespuestaContactos ObtenerContactos(global::ChatGrpc.SolicitudObtenerContactos request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ObtenerContactos(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::ChatGrpc.RespuestaContactos ObtenerContactos(global::ChatGrpc.SolicitudObtenerContactos request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ObtenerContactos, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::ChatGrpc.RespuestaContactos> ObtenerContactosAsync(global::ChatGrpc.SolicitudObtenerContactos request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ObtenerContactosAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::ChatGrpc.RespuestaContactos> ObtenerContactosAsync(global::ChatGrpc.SolicitudObtenerContactos request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ObtenerContactos, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override ServicioChatClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ServicioChatClient(configuration);
      }
    }

  }
}
#endregion
