// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Grpc/Protos/multimedia.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace MultimediaGrpc {
  public static partial class ServicioMultimedia
  {
    static readonly string __ServiceName = "multimedia.ServicioMultimedia";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::MultimediaGrpc.ChunkArchivo> __Marshaller_multimedia_ChunkArchivo = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::MultimediaGrpc.ChunkArchivo.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::MultimediaGrpc.RespuestaGeneral> __Marshaller_multimedia_RespuestaGeneral = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::MultimediaGrpc.RespuestaGeneral.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::MultimediaGrpc.ChunkArchivo, global::MultimediaGrpc.RespuestaGeneral> __Method_SubirFotoUsuario = new grpc::Method<global::MultimediaGrpc.ChunkArchivo, global::MultimediaGrpc.RespuestaGeneral>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "SubirFotoUsuario",
        __Marshaller_multimedia_ChunkArchivo,
        __Marshaller_multimedia_RespuestaGeneral);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::MultimediaGrpc.ChunkArchivo, global::MultimediaGrpc.RespuestaGeneral> __Method_SubirFotoMascota = new grpc::Method<global::MultimediaGrpc.ChunkArchivo, global::MultimediaGrpc.RespuestaGeneral>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "SubirFotoMascota",
        __Marshaller_multimedia_ChunkArchivo,
        __Marshaller_multimedia_RespuestaGeneral);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::MultimediaGrpc.ChunkArchivo, global::MultimediaGrpc.RespuestaGeneral> __Method_SubirVideoMascota = new grpc::Method<global::MultimediaGrpc.ChunkArchivo, global::MultimediaGrpc.RespuestaGeneral>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "SubirVideoMascota",
        __Marshaller_multimedia_ChunkArchivo,
        __Marshaller_multimedia_RespuestaGeneral);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::MultimediaGrpc.MultimediaReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for ServicioMultimedia</summary>
    public partial class ServicioMultimediaClient : grpc::ClientBase<ServicioMultimediaClient>
    {
      /// <summary>Creates a new client for ServicioMultimedia</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ServicioMultimediaClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ServicioMultimedia that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ServicioMultimediaClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ServicioMultimediaClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ServicioMultimediaClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::MultimediaGrpc.ChunkArchivo, global::MultimediaGrpc.RespuestaGeneral> SubirFotoUsuario(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SubirFotoUsuario(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::MultimediaGrpc.ChunkArchivo, global::MultimediaGrpc.RespuestaGeneral> SubirFotoUsuario(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_SubirFotoUsuario, null, options);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::MultimediaGrpc.ChunkArchivo, global::MultimediaGrpc.RespuestaGeneral> SubirFotoMascota(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SubirFotoMascota(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::MultimediaGrpc.ChunkArchivo, global::MultimediaGrpc.RespuestaGeneral> SubirFotoMascota(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_SubirFotoMascota, null, options);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::MultimediaGrpc.ChunkArchivo, global::MultimediaGrpc.RespuestaGeneral> SubirVideoMascota(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SubirVideoMascota(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::MultimediaGrpc.ChunkArchivo, global::MultimediaGrpc.RespuestaGeneral> SubirVideoMascota(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_SubirVideoMascota, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override ServicioMultimediaClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ServicioMultimediaClient(configuration);
      }
    }

  }
}
#endregion
