// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Grpc/Protos/notificacion.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NotificacionGrpc {

  /// <summary>Holder for reflection information generated from Grpc/Protos/notificacion.proto</summary>
  public static partial class NotificacionReflection {

    #region Descriptor
    /// <summary>File descriptor for Grpc/Protos/notificacion.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NotificacionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5HcnBjL1Byb3Rvcy9ub3RpZmljYWNpb24ucHJvdG8SDG5vdGlmaWNhY2lv",
            "biIeCglVc3VhcmlvSUQSEQoJdXN1YXJpb0lkGAEgASgFIpIBChFOb3RpZmlj",
            "YWNpb25JbnB1dBIRCgl1c3VhcmlvSWQYASABKAUSDgoGdGl0dWxvGAIgASgJ",
            "Eg8KB21lbnNhamUYAyABKAkSDAoEdGlwbxgEIAEoCRIUCgxyZWZlcmVuY2lh",
            "SWQYBSABKAUSFgoOcmVmZXJlbmNpYVRpcG8YBiABKAkSDQoFZmVjaGEYByAB",
            "KAkiegoMTm90aWZpY2FjaW9uEg4KBnRpdHVsbxgBIAEoCRIPCgdtZW5zYWpl",
            "GAIgASgJEgwKBHRpcG8YAyABKAkSFAoMcmVmZXJlbmNpYUlkGAQgASgFEhYK",
            "DnJlZmVyZW5jaWFUaXBvGAUgASgJEg0KBWZlY2hhGAYgASgJIisKCVJlc3B1",
            "ZXN0YRINCgVleGl0bxgBIAEoCBIPCgdtZW5zYWplGAIgASgJIgcKBUVtcHR5",
            "MrMBChRTZXJ2aWNpb05vdGlmaWNhY2lvbhJLChZFc2N1Y2hhck5vdGlmaWNh",
            "Y2lvbmVzEhMubm90aWZpY2FjaW9uLkVtcHR5Ghoubm90aWZpY2FjaW9uLk5v",
            "dGlmaWNhY2lvbjABEk4KEkVudmlhck5vdGlmaWNhY2lvbhIfLm5vdGlmaWNh",
            "Y2lvbi5Ob3RpZmljYWNpb25JbnB1dBoXLm5vdGlmaWNhY2lvbi5SZXNwdWVz",
            "dGFCE6oCEE5vdGlmaWNhY2lvbkdycGNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::NotificacionGrpc.UsuarioID), global::NotificacionGrpc.UsuarioID.Parser, new[]{ "UsuarioId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NotificacionGrpc.NotificacionInput), global::NotificacionGrpc.NotificacionInput.Parser, new[]{ "UsuarioId", "Titulo", "Mensaje", "Tipo", "ReferenciaId", "ReferenciaTipo", "Fecha" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NotificacionGrpc.Notificacion), global::NotificacionGrpc.Notificacion.Parser, new[]{ "Titulo", "Mensaje", "Tipo", "ReferenciaId", "ReferenciaTipo", "Fecha" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NotificacionGrpc.Respuesta), global::NotificacionGrpc.Respuesta.Parser, new[]{ "Exito", "Mensaje" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NotificacionGrpc.Empty), global::NotificacionGrpc.Empty.Parser, null, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UsuarioID : pb::IMessage<UsuarioID>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UsuarioID> _parser = new pb::MessageParser<UsuarioID>(() => new UsuarioID());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UsuarioID> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NotificacionGrpc.NotificacionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UsuarioID() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UsuarioID(UsuarioID other) : this() {
      usuarioId_ = other.usuarioId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UsuarioID Clone() {
      return new UsuarioID(this);
    }

    /// <summary>Field number for the "usuarioId" field.</summary>
    public const int UsuarioIdFieldNumber = 1;
    private int usuarioId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int UsuarioId {
      get { return usuarioId_; }
      set {
        usuarioId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UsuarioID);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UsuarioID other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UsuarioId != other.UsuarioId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UsuarioId != 0) hash ^= UsuarioId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UsuarioId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UsuarioId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UsuarioId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UsuarioId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UsuarioId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UsuarioId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UsuarioID other) {
      if (other == null) {
        return;
      }
      if (other.UsuarioId != 0) {
        UsuarioId = other.UsuarioId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            UsuarioId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            UsuarioId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class NotificacionInput : pb::IMessage<NotificacionInput>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NotificacionInput> _parser = new pb::MessageParser<NotificacionInput>(() => new NotificacionInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NotificacionInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NotificacionGrpc.NotificacionReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NotificacionInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NotificacionInput(NotificacionInput other) : this() {
      usuarioId_ = other.usuarioId_;
      titulo_ = other.titulo_;
      mensaje_ = other.mensaje_;
      tipo_ = other.tipo_;
      referenciaId_ = other.referenciaId_;
      referenciaTipo_ = other.referenciaTipo_;
      fecha_ = other.fecha_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NotificacionInput Clone() {
      return new NotificacionInput(this);
    }

    /// <summary>Field number for the "usuarioId" field.</summary>
    public const int UsuarioIdFieldNumber = 1;
    private int usuarioId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int UsuarioId {
      get { return usuarioId_; }
      set {
        usuarioId_ = value;
      }
    }

    /// <summary>Field number for the "titulo" field.</summary>
    public const int TituloFieldNumber = 2;
    private string titulo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Titulo {
      get { return titulo_; }
      set {
        titulo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mensaje" field.</summary>
    public const int MensajeFieldNumber = 3;
    private string mensaje_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Mensaje {
      get { return mensaje_; }
      set {
        mensaje_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tipo" field.</summary>
    public const int TipoFieldNumber = 4;
    private string tipo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Tipo {
      get { return tipo_; }
      set {
        tipo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "referenciaId" field.</summary>
    public const int ReferenciaIdFieldNumber = 5;
    private int referenciaId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ReferenciaId {
      get { return referenciaId_; }
      set {
        referenciaId_ = value;
      }
    }

    /// <summary>Field number for the "referenciaTipo" field.</summary>
    public const int ReferenciaTipoFieldNumber = 6;
    private string referenciaTipo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ReferenciaTipo {
      get { return referenciaTipo_; }
      set {
        referenciaTipo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "fecha" field.</summary>
    public const int FechaFieldNumber = 7;
    private string fecha_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Fecha {
      get { return fecha_; }
      set {
        fecha_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NotificacionInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NotificacionInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UsuarioId != other.UsuarioId) return false;
      if (Titulo != other.Titulo) return false;
      if (Mensaje != other.Mensaje) return false;
      if (Tipo != other.Tipo) return false;
      if (ReferenciaId != other.ReferenciaId) return false;
      if (ReferenciaTipo != other.ReferenciaTipo) return false;
      if (Fecha != other.Fecha) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UsuarioId != 0) hash ^= UsuarioId.GetHashCode();
      if (Titulo.Length != 0) hash ^= Titulo.GetHashCode();
      if (Mensaje.Length != 0) hash ^= Mensaje.GetHashCode();
      if (Tipo.Length != 0) hash ^= Tipo.GetHashCode();
      if (ReferenciaId != 0) hash ^= ReferenciaId.GetHashCode();
      if (ReferenciaTipo.Length != 0) hash ^= ReferenciaTipo.GetHashCode();
      if (Fecha.Length != 0) hash ^= Fecha.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UsuarioId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UsuarioId);
      }
      if (Titulo.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Titulo);
      }
      if (Mensaje.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Mensaje);
      }
      if (Tipo.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Tipo);
      }
      if (ReferenciaId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ReferenciaId);
      }
      if (ReferenciaTipo.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ReferenciaTipo);
      }
      if (Fecha.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Fecha);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UsuarioId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UsuarioId);
      }
      if (Titulo.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Titulo);
      }
      if (Mensaje.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Mensaje);
      }
      if (Tipo.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Tipo);
      }
      if (ReferenciaId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ReferenciaId);
      }
      if (ReferenciaTipo.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ReferenciaTipo);
      }
      if (Fecha.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Fecha);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UsuarioId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UsuarioId);
      }
      if (Titulo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Titulo);
      }
      if (Mensaje.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mensaje);
      }
      if (Tipo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Tipo);
      }
      if (ReferenciaId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ReferenciaId);
      }
      if (ReferenciaTipo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ReferenciaTipo);
      }
      if (Fecha.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Fecha);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NotificacionInput other) {
      if (other == null) {
        return;
      }
      if (other.UsuarioId != 0) {
        UsuarioId = other.UsuarioId;
      }
      if (other.Titulo.Length != 0) {
        Titulo = other.Titulo;
      }
      if (other.Mensaje.Length != 0) {
        Mensaje = other.Mensaje;
      }
      if (other.Tipo.Length != 0) {
        Tipo = other.Tipo;
      }
      if (other.ReferenciaId != 0) {
        ReferenciaId = other.ReferenciaId;
      }
      if (other.ReferenciaTipo.Length != 0) {
        ReferenciaTipo = other.ReferenciaTipo;
      }
      if (other.Fecha.Length != 0) {
        Fecha = other.Fecha;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            UsuarioId = input.ReadInt32();
            break;
          }
          case 18: {
            Titulo = input.ReadString();
            break;
          }
          case 26: {
            Mensaje = input.ReadString();
            break;
          }
          case 34: {
            Tipo = input.ReadString();
            break;
          }
          case 40: {
            ReferenciaId = input.ReadInt32();
            break;
          }
          case 50: {
            ReferenciaTipo = input.ReadString();
            break;
          }
          case 58: {
            Fecha = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            UsuarioId = input.ReadInt32();
            break;
          }
          case 18: {
            Titulo = input.ReadString();
            break;
          }
          case 26: {
            Mensaje = input.ReadString();
            break;
          }
          case 34: {
            Tipo = input.ReadString();
            break;
          }
          case 40: {
            ReferenciaId = input.ReadInt32();
            break;
          }
          case 50: {
            ReferenciaTipo = input.ReadString();
            break;
          }
          case 58: {
            Fecha = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Notificacion : pb::IMessage<Notificacion>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Notificacion> _parser = new pb::MessageParser<Notificacion>(() => new Notificacion());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Notificacion> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NotificacionGrpc.NotificacionReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Notificacion() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Notificacion(Notificacion other) : this() {
      titulo_ = other.titulo_;
      mensaje_ = other.mensaje_;
      tipo_ = other.tipo_;
      referenciaId_ = other.referenciaId_;
      referenciaTipo_ = other.referenciaTipo_;
      fecha_ = other.fecha_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Notificacion Clone() {
      return new Notificacion(this);
    }

    /// <summary>Field number for the "titulo" field.</summary>
    public const int TituloFieldNumber = 1;
    private string titulo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Titulo {
      get { return titulo_; }
      set {
        titulo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mensaje" field.</summary>
    public const int MensajeFieldNumber = 2;
    private string mensaje_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Mensaje {
      get { return mensaje_; }
      set {
        mensaje_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tipo" field.</summary>
    public const int TipoFieldNumber = 3;
    private string tipo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Tipo {
      get { return tipo_; }
      set {
        tipo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "referenciaId" field.</summary>
    public const int ReferenciaIdFieldNumber = 4;
    private int referenciaId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ReferenciaId {
      get { return referenciaId_; }
      set {
        referenciaId_ = value;
      }
    }

    /// <summary>Field number for the "referenciaTipo" field.</summary>
    public const int ReferenciaTipoFieldNumber = 5;
    private string referenciaTipo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ReferenciaTipo {
      get { return referenciaTipo_; }
      set {
        referenciaTipo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "fecha" field.</summary>
    public const int FechaFieldNumber = 6;
    private string fecha_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Fecha {
      get { return fecha_; }
      set {
        fecha_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Notificacion);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Notificacion other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Titulo != other.Titulo) return false;
      if (Mensaje != other.Mensaje) return false;
      if (Tipo != other.Tipo) return false;
      if (ReferenciaId != other.ReferenciaId) return false;
      if (ReferenciaTipo != other.ReferenciaTipo) return false;
      if (Fecha != other.Fecha) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Titulo.Length != 0) hash ^= Titulo.GetHashCode();
      if (Mensaje.Length != 0) hash ^= Mensaje.GetHashCode();
      if (Tipo.Length != 0) hash ^= Tipo.GetHashCode();
      if (ReferenciaId != 0) hash ^= ReferenciaId.GetHashCode();
      if (ReferenciaTipo.Length != 0) hash ^= ReferenciaTipo.GetHashCode();
      if (Fecha.Length != 0) hash ^= Fecha.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Titulo.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Titulo);
      }
      if (Mensaje.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Mensaje);
      }
      if (Tipo.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Tipo);
      }
      if (ReferenciaId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ReferenciaId);
      }
      if (ReferenciaTipo.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ReferenciaTipo);
      }
      if (Fecha.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Fecha);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Titulo.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Titulo);
      }
      if (Mensaje.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Mensaje);
      }
      if (Tipo.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Tipo);
      }
      if (ReferenciaId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ReferenciaId);
      }
      if (ReferenciaTipo.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ReferenciaTipo);
      }
      if (Fecha.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Fecha);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Titulo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Titulo);
      }
      if (Mensaje.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mensaje);
      }
      if (Tipo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Tipo);
      }
      if (ReferenciaId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ReferenciaId);
      }
      if (ReferenciaTipo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ReferenciaTipo);
      }
      if (Fecha.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Fecha);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Notificacion other) {
      if (other == null) {
        return;
      }
      if (other.Titulo.Length != 0) {
        Titulo = other.Titulo;
      }
      if (other.Mensaje.Length != 0) {
        Mensaje = other.Mensaje;
      }
      if (other.Tipo.Length != 0) {
        Tipo = other.Tipo;
      }
      if (other.ReferenciaId != 0) {
        ReferenciaId = other.ReferenciaId;
      }
      if (other.ReferenciaTipo.Length != 0) {
        ReferenciaTipo = other.ReferenciaTipo;
      }
      if (other.Fecha.Length != 0) {
        Fecha = other.Fecha;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Titulo = input.ReadString();
            break;
          }
          case 18: {
            Mensaje = input.ReadString();
            break;
          }
          case 26: {
            Tipo = input.ReadString();
            break;
          }
          case 32: {
            ReferenciaId = input.ReadInt32();
            break;
          }
          case 42: {
            ReferenciaTipo = input.ReadString();
            break;
          }
          case 50: {
            Fecha = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Titulo = input.ReadString();
            break;
          }
          case 18: {
            Mensaje = input.ReadString();
            break;
          }
          case 26: {
            Tipo = input.ReadString();
            break;
          }
          case 32: {
            ReferenciaId = input.ReadInt32();
            break;
          }
          case 42: {
            ReferenciaTipo = input.ReadString();
            break;
          }
          case 50: {
            Fecha = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Respuesta : pb::IMessage<Respuesta>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Respuesta> _parser = new pb::MessageParser<Respuesta>(() => new Respuesta());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Respuesta> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NotificacionGrpc.NotificacionReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Respuesta() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Respuesta(Respuesta other) : this() {
      exito_ = other.exito_;
      mensaje_ = other.mensaje_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Respuesta Clone() {
      return new Respuesta(this);
    }

    /// <summary>Field number for the "exito" field.</summary>
    public const int ExitoFieldNumber = 1;
    private bool exito_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Exito {
      get { return exito_; }
      set {
        exito_ = value;
      }
    }

    /// <summary>Field number for the "mensaje" field.</summary>
    public const int MensajeFieldNumber = 2;
    private string mensaje_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Mensaje {
      get { return mensaje_; }
      set {
        mensaje_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Respuesta);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Respuesta other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Exito != other.Exito) return false;
      if (Mensaje != other.Mensaje) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Exito != false) hash ^= Exito.GetHashCode();
      if (Mensaje.Length != 0) hash ^= Mensaje.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Exito != false) {
        output.WriteRawTag(8);
        output.WriteBool(Exito);
      }
      if (Mensaje.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Mensaje);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Exito != false) {
        output.WriteRawTag(8);
        output.WriteBool(Exito);
      }
      if (Mensaje.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Mensaje);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Exito != false) {
        size += 1 + 1;
      }
      if (Mensaje.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mensaje);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Respuesta other) {
      if (other == null) {
        return;
      }
      if (other.Exito != false) {
        Exito = other.Exito;
      }
      if (other.Mensaje.Length != 0) {
        Mensaje = other.Mensaje;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Exito = input.ReadBool();
            break;
          }
          case 18: {
            Mensaje = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Exito = input.ReadBool();
            break;
          }
          case 18: {
            Mensaje = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Empty : pb::IMessage<Empty>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Empty> _parser = new pb::MessageParser<Empty>(() => new Empty());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Empty> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NotificacionGrpc.NotificacionReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Empty() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Empty(Empty other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Empty Clone() {
      return new Empty(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Empty);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Empty other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Empty other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
