// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Grpc/Protos/ubicacion.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace UbicacionGrpc {

  /// <summary>Holder for reflection information generated from Grpc/Protos/ubicacion.proto</summary>
  public static partial class UbicacionReflection {

    #region Descriptor
    /// <summary>File descriptor for Grpc/Protos/ubicacion.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UbicacionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtHcnBjL1Byb3Rvcy91YmljYWNpb24ucHJvdG8SCXViaWNhY2lvbiJBCglV",
            "YmljYWNpb24SEQoJdXN1YXJpb0lkGAEgASgFEhAKCGxvbmdpdHVkGAIgASgB",
            "Eg8KB2xhdGl0dWQYAyABKAEiigEKEFNvbGljaXR1ZENlcmNhbmESGwoTc29s",
            "aWNpdHVkQWRvcGNpb25JZBgBIAEoBRIRCglkaXN0YW5jaWEYAiABKAESEAoI",
            "bG9uZ2l0dWQYAyABKAESDwoHbGF0aXR1ZBgEIAEoARIjCgdtYXNjb3RhGAUg",
            "ASgLMhIudWJpY2FjaW9uLk1hc2NvdGEijAEKB01hc2NvdGESEQoJbWFzY290",
            "YUlkGAEgASgFEg4KBm5vbWJyZRgCIAEoCRIPCgdlc3BlY2llGAMgASgJEgwK",
            "BHJhemEYBCABKAkSDAoEZWRhZBgFIAEoCRIMCgRzZXhvGAYgASgJEg4KBnRh",
            "bWFubxgHIAEoCRITCgtkZXNjcmlwY2lvbhgIIAEoCSJGChNTb2xpY2l0dWRl",
            "c0NlcmNhbmFzEi8KCnJlc3VsdGFkb3MYASADKAsyGy51YmljYWNpb24uU29s",
            "aWNpdHVkQ2VyY2FuYSIHCgVFbXB0eTKmAQoRU2VydmljaW9VYmljYWNpb24S",
            "PQoTQWN0dWFsaXphclViaWNhY2lvbhIULnViaWNhY2lvbi5VYmljYWNpb24a",
            "EC51YmljYWNpb24uRW1wdHkSUgoaT2J0ZW5lclNvbGljaXR1ZGVzQ2VyY2Fu",
            "YXMSFC51YmljYWNpb24uVWJpY2FjaW9uGh4udWJpY2FjaW9uLlNvbGljaXR1",
            "ZGVzQ2VyY2FuYXNCEKoCDVViaWNhY2lvbkdycGNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::UbicacionGrpc.Ubicacion), global::UbicacionGrpc.Ubicacion.Parser, new[]{ "UsuarioId", "Longitud", "Latitud" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::UbicacionGrpc.SolicitudCercana), global::UbicacionGrpc.SolicitudCercana.Parser, new[]{ "SolicitudAdopcionId", "Distancia", "Longitud", "Latitud", "Mascota" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::UbicacionGrpc.Mascota), global::UbicacionGrpc.Mascota.Parser, new[]{ "MascotaId", "Nombre", "Especie", "Raza", "Edad", "Sexo", "Tamano", "Descripcion" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::UbicacionGrpc.SolicitudesCercanas), global::UbicacionGrpc.SolicitudesCercanas.Parser, new[]{ "Resultados" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::UbicacionGrpc.Empty), global::UbicacionGrpc.Empty.Parser, null, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Ubicacion : pb::IMessage<Ubicacion>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Ubicacion> _parser = new pb::MessageParser<Ubicacion>(() => new Ubicacion());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Ubicacion> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UbicacionGrpc.UbicacionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Ubicacion() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Ubicacion(Ubicacion other) : this() {
      usuarioId_ = other.usuarioId_;
      longitud_ = other.longitud_;
      latitud_ = other.latitud_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Ubicacion Clone() {
      return new Ubicacion(this);
    }

    /// <summary>Field number for the "usuarioId" field.</summary>
    public const int UsuarioIdFieldNumber = 1;
    private int usuarioId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int UsuarioId {
      get { return usuarioId_; }
      set {
        usuarioId_ = value;
      }
    }

    /// <summary>Field number for the "longitud" field.</summary>
    public const int LongitudFieldNumber = 2;
    private double longitud_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Longitud {
      get { return longitud_; }
      set {
        longitud_ = value;
      }
    }

    /// <summary>Field number for the "latitud" field.</summary>
    public const int LatitudFieldNumber = 3;
    private double latitud_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Latitud {
      get { return latitud_; }
      set {
        latitud_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Ubicacion);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Ubicacion other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UsuarioId != other.UsuarioId) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Longitud, other.Longitud)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Latitud, other.Latitud)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UsuarioId != 0) hash ^= UsuarioId.GetHashCode();
      if (Longitud != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Longitud);
      if (Latitud != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Latitud);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UsuarioId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UsuarioId);
      }
      if (Longitud != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Longitud);
      }
      if (Latitud != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Latitud);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UsuarioId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UsuarioId);
      }
      if (Longitud != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Longitud);
      }
      if (Latitud != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Latitud);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UsuarioId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UsuarioId);
      }
      if (Longitud != 0D) {
        size += 1 + 8;
      }
      if (Latitud != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Ubicacion other) {
      if (other == null) {
        return;
      }
      if (other.UsuarioId != 0) {
        UsuarioId = other.UsuarioId;
      }
      if (other.Longitud != 0D) {
        Longitud = other.Longitud;
      }
      if (other.Latitud != 0D) {
        Latitud = other.Latitud;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            UsuarioId = input.ReadInt32();
            break;
          }
          case 17: {
            Longitud = input.ReadDouble();
            break;
          }
          case 25: {
            Latitud = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            UsuarioId = input.ReadInt32();
            break;
          }
          case 17: {
            Longitud = input.ReadDouble();
            break;
          }
          case 25: {
            Latitud = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SolicitudCercana : pb::IMessage<SolicitudCercana>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SolicitudCercana> _parser = new pb::MessageParser<SolicitudCercana>(() => new SolicitudCercana());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SolicitudCercana> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UbicacionGrpc.UbicacionReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SolicitudCercana() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SolicitudCercana(SolicitudCercana other) : this() {
      solicitudAdopcionId_ = other.solicitudAdopcionId_;
      distancia_ = other.distancia_;
      longitud_ = other.longitud_;
      latitud_ = other.latitud_;
      mascota_ = other.mascota_ != null ? other.mascota_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SolicitudCercana Clone() {
      return new SolicitudCercana(this);
    }

    /// <summary>Field number for the "solicitudAdopcionId" field.</summary>
    public const int SolicitudAdopcionIdFieldNumber = 1;
    private int solicitudAdopcionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SolicitudAdopcionId {
      get { return solicitudAdopcionId_; }
      set {
        solicitudAdopcionId_ = value;
      }
    }

    /// <summary>Field number for the "distancia" field.</summary>
    public const int DistanciaFieldNumber = 2;
    private double distancia_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Distancia {
      get { return distancia_; }
      set {
        distancia_ = value;
      }
    }

    /// <summary>Field number for the "longitud" field.</summary>
    public const int LongitudFieldNumber = 3;
    private double longitud_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Longitud {
      get { return longitud_; }
      set {
        longitud_ = value;
      }
    }

    /// <summary>Field number for the "latitud" field.</summary>
    public const int LatitudFieldNumber = 4;
    private double latitud_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Latitud {
      get { return latitud_; }
      set {
        latitud_ = value;
      }
    }

    /// <summary>Field number for the "mascota" field.</summary>
    public const int MascotaFieldNumber = 5;
    private global::UbicacionGrpc.Mascota mascota_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::UbicacionGrpc.Mascota Mascota {
      get { return mascota_; }
      set {
        mascota_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SolicitudCercana);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SolicitudCercana other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SolicitudAdopcionId != other.SolicitudAdopcionId) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Distancia, other.Distancia)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Longitud, other.Longitud)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Latitud, other.Latitud)) return false;
      if (!object.Equals(Mascota, other.Mascota)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SolicitudAdopcionId != 0) hash ^= SolicitudAdopcionId.GetHashCode();
      if (Distancia != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Distancia);
      if (Longitud != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Longitud);
      if (Latitud != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Latitud);
      if (mascota_ != null) hash ^= Mascota.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SolicitudAdopcionId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SolicitudAdopcionId);
      }
      if (Distancia != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Distancia);
      }
      if (Longitud != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Longitud);
      }
      if (Latitud != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Latitud);
      }
      if (mascota_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Mascota);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SolicitudAdopcionId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SolicitudAdopcionId);
      }
      if (Distancia != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Distancia);
      }
      if (Longitud != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Longitud);
      }
      if (Latitud != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Latitud);
      }
      if (mascota_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Mascota);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SolicitudAdopcionId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SolicitudAdopcionId);
      }
      if (Distancia != 0D) {
        size += 1 + 8;
      }
      if (Longitud != 0D) {
        size += 1 + 8;
      }
      if (Latitud != 0D) {
        size += 1 + 8;
      }
      if (mascota_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Mascota);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SolicitudCercana other) {
      if (other == null) {
        return;
      }
      if (other.SolicitudAdopcionId != 0) {
        SolicitudAdopcionId = other.SolicitudAdopcionId;
      }
      if (other.Distancia != 0D) {
        Distancia = other.Distancia;
      }
      if (other.Longitud != 0D) {
        Longitud = other.Longitud;
      }
      if (other.Latitud != 0D) {
        Latitud = other.Latitud;
      }
      if (other.mascota_ != null) {
        if (mascota_ == null) {
          Mascota = new global::UbicacionGrpc.Mascota();
        }
        Mascota.MergeFrom(other.Mascota);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SolicitudAdopcionId = input.ReadInt32();
            break;
          }
          case 17: {
            Distancia = input.ReadDouble();
            break;
          }
          case 25: {
            Longitud = input.ReadDouble();
            break;
          }
          case 33: {
            Latitud = input.ReadDouble();
            break;
          }
          case 42: {
            if (mascota_ == null) {
              Mascota = new global::UbicacionGrpc.Mascota();
            }
            input.ReadMessage(Mascota);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SolicitudAdopcionId = input.ReadInt32();
            break;
          }
          case 17: {
            Distancia = input.ReadDouble();
            break;
          }
          case 25: {
            Longitud = input.ReadDouble();
            break;
          }
          case 33: {
            Latitud = input.ReadDouble();
            break;
          }
          case 42: {
            if (mascota_ == null) {
              Mascota = new global::UbicacionGrpc.Mascota();
            }
            input.ReadMessage(Mascota);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Mascota : pb::IMessage<Mascota>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Mascota> _parser = new pb::MessageParser<Mascota>(() => new Mascota());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Mascota> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UbicacionGrpc.UbicacionReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Mascota() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Mascota(Mascota other) : this() {
      mascotaId_ = other.mascotaId_;
      nombre_ = other.nombre_;
      especie_ = other.especie_;
      raza_ = other.raza_;
      edad_ = other.edad_;
      sexo_ = other.sexo_;
      tamano_ = other.tamano_;
      descripcion_ = other.descripcion_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Mascota Clone() {
      return new Mascota(this);
    }

    /// <summary>Field number for the "mascotaId" field.</summary>
    public const int MascotaIdFieldNumber = 1;
    private int mascotaId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MascotaId {
      get { return mascotaId_; }
      set {
        mascotaId_ = value;
      }
    }

    /// <summary>Field number for the "nombre" field.</summary>
    public const int NombreFieldNumber = 2;
    private string nombre_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Nombre {
      get { return nombre_; }
      set {
        nombre_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "especie" field.</summary>
    public const int EspecieFieldNumber = 3;
    private string especie_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Especie {
      get { return especie_; }
      set {
        especie_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "raza" field.</summary>
    public const int RazaFieldNumber = 4;
    private string raza_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Raza {
      get { return raza_; }
      set {
        raza_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "edad" field.</summary>
    public const int EdadFieldNumber = 5;
    private string edad_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Edad {
      get { return edad_; }
      set {
        edad_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sexo" field.</summary>
    public const int SexoFieldNumber = 6;
    private string sexo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Sexo {
      get { return sexo_; }
      set {
        sexo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tamano" field.</summary>
    public const int TamanoFieldNumber = 7;
    private string tamano_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Tamano {
      get { return tamano_; }
      set {
        tamano_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "descripcion" field.</summary>
    public const int DescripcionFieldNumber = 8;
    private string descripcion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Descripcion {
      get { return descripcion_; }
      set {
        descripcion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Mascota);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Mascota other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MascotaId != other.MascotaId) return false;
      if (Nombre != other.Nombre) return false;
      if (Especie != other.Especie) return false;
      if (Raza != other.Raza) return false;
      if (Edad != other.Edad) return false;
      if (Sexo != other.Sexo) return false;
      if (Tamano != other.Tamano) return false;
      if (Descripcion != other.Descripcion) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MascotaId != 0) hash ^= MascotaId.GetHashCode();
      if (Nombre.Length != 0) hash ^= Nombre.GetHashCode();
      if (Especie.Length != 0) hash ^= Especie.GetHashCode();
      if (Raza.Length != 0) hash ^= Raza.GetHashCode();
      if (Edad.Length != 0) hash ^= Edad.GetHashCode();
      if (Sexo.Length != 0) hash ^= Sexo.GetHashCode();
      if (Tamano.Length != 0) hash ^= Tamano.GetHashCode();
      if (Descripcion.Length != 0) hash ^= Descripcion.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MascotaId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MascotaId);
      }
      if (Nombre.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nombre);
      }
      if (Especie.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Especie);
      }
      if (Raza.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Raza);
      }
      if (Edad.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Edad);
      }
      if (Sexo.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Sexo);
      }
      if (Tamano.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Tamano);
      }
      if (Descripcion.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Descripcion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MascotaId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MascotaId);
      }
      if (Nombre.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nombre);
      }
      if (Especie.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Especie);
      }
      if (Raza.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Raza);
      }
      if (Edad.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Edad);
      }
      if (Sexo.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Sexo);
      }
      if (Tamano.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Tamano);
      }
      if (Descripcion.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Descripcion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MascotaId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MascotaId);
      }
      if (Nombre.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nombre);
      }
      if (Especie.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Especie);
      }
      if (Raza.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Raza);
      }
      if (Edad.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Edad);
      }
      if (Sexo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Sexo);
      }
      if (Tamano.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Tamano);
      }
      if (Descripcion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Descripcion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Mascota other) {
      if (other == null) {
        return;
      }
      if (other.MascotaId != 0) {
        MascotaId = other.MascotaId;
      }
      if (other.Nombre.Length != 0) {
        Nombre = other.Nombre;
      }
      if (other.Especie.Length != 0) {
        Especie = other.Especie;
      }
      if (other.Raza.Length != 0) {
        Raza = other.Raza;
      }
      if (other.Edad.Length != 0) {
        Edad = other.Edad;
      }
      if (other.Sexo.Length != 0) {
        Sexo = other.Sexo;
      }
      if (other.Tamano.Length != 0) {
        Tamano = other.Tamano;
      }
      if (other.Descripcion.Length != 0) {
        Descripcion = other.Descripcion;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MascotaId = input.ReadInt32();
            break;
          }
          case 18: {
            Nombre = input.ReadString();
            break;
          }
          case 26: {
            Especie = input.ReadString();
            break;
          }
          case 34: {
            Raza = input.ReadString();
            break;
          }
          case 42: {
            Edad = input.ReadString();
            break;
          }
          case 50: {
            Sexo = input.ReadString();
            break;
          }
          case 58: {
            Tamano = input.ReadString();
            break;
          }
          case 66: {
            Descripcion = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MascotaId = input.ReadInt32();
            break;
          }
          case 18: {
            Nombre = input.ReadString();
            break;
          }
          case 26: {
            Especie = input.ReadString();
            break;
          }
          case 34: {
            Raza = input.ReadString();
            break;
          }
          case 42: {
            Edad = input.ReadString();
            break;
          }
          case 50: {
            Sexo = input.ReadString();
            break;
          }
          case 58: {
            Tamano = input.ReadString();
            break;
          }
          case 66: {
            Descripcion = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SolicitudesCercanas : pb::IMessage<SolicitudesCercanas>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SolicitudesCercanas> _parser = new pb::MessageParser<SolicitudesCercanas>(() => new SolicitudesCercanas());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SolicitudesCercanas> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UbicacionGrpc.UbicacionReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SolicitudesCercanas() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SolicitudesCercanas(SolicitudesCercanas other) : this() {
      resultados_ = other.resultados_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SolicitudesCercanas Clone() {
      return new SolicitudesCercanas(this);
    }

    /// <summary>Field number for the "resultados" field.</summary>
    public const int ResultadosFieldNumber = 1;
    private static readonly pb::FieldCodec<global::UbicacionGrpc.SolicitudCercana> _repeated_resultados_codec
        = pb::FieldCodec.ForMessage(10, global::UbicacionGrpc.SolicitudCercana.Parser);
    private readonly pbc::RepeatedField<global::UbicacionGrpc.SolicitudCercana> resultados_ = new pbc::RepeatedField<global::UbicacionGrpc.SolicitudCercana>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::UbicacionGrpc.SolicitudCercana> Resultados {
      get { return resultados_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SolicitudesCercanas);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SolicitudesCercanas other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!resultados_.Equals(other.resultados_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= resultados_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      resultados_.WriteTo(output, _repeated_resultados_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      resultados_.WriteTo(ref output, _repeated_resultados_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += resultados_.CalculateSize(_repeated_resultados_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SolicitudesCercanas other) {
      if (other == null) {
        return;
      }
      resultados_.Add(other.resultados_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            resultados_.AddEntriesFrom(input, _repeated_resultados_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            resultados_.AddEntriesFrom(ref input, _repeated_resultados_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Empty : pb::IMessage<Empty>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Empty> _parser = new pb::MessageParser<Empty>(() => new Empty());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Empty> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UbicacionGrpc.UbicacionReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Empty() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Empty(Empty other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Empty Clone() {
      return new Empty(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Empty);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Empty other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Empty other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
