// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Grpc/Protos/ubicacion.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace UbicacionGrpc {
  public static partial class ServicioUbicacion
  {
    static readonly string __ServiceName = "ubicacion.ServicioUbicacion";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::UbicacionGrpc.Ubicacion> __Marshaller_ubicacion_Ubicacion = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::UbicacionGrpc.Ubicacion.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::UbicacionGrpc.Empty> __Marshaller_ubicacion_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::UbicacionGrpc.Empty.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::UbicacionGrpc.AdopcionesCercanas> __Marshaller_ubicacion_AdopcionesCercanas = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::UbicacionGrpc.AdopcionesCercanas.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::UbicacionGrpc.Ubicacion, global::UbicacionGrpc.Empty> __Method_ActualizarUbicacion = new grpc::Method<global::UbicacionGrpc.Ubicacion, global::UbicacionGrpc.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ActualizarUbicacion",
        __Marshaller_ubicacion_Ubicacion,
        __Marshaller_ubicacion_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::UbicacionGrpc.Ubicacion, global::UbicacionGrpc.AdopcionesCercanas> __Method_ObtenerAdopcionesCercanas = new grpc::Method<global::UbicacionGrpc.Ubicacion, global::UbicacionGrpc.AdopcionesCercanas>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ObtenerAdopcionesCercanas",
        __Marshaller_ubicacion_Ubicacion,
        __Marshaller_ubicacion_AdopcionesCercanas);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::UbicacionGrpc.UbicacionReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for ServicioUbicacion</summary>
    public partial class ServicioUbicacionClient : grpc::ClientBase<ServicioUbicacionClient>
    {
      /// <summary>Creates a new client for ServicioUbicacion</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ServicioUbicacionClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ServicioUbicacion that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ServicioUbicacionClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ServicioUbicacionClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ServicioUbicacionClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UbicacionGrpc.Empty ActualizarUbicacion(global::UbicacionGrpc.Ubicacion request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ActualizarUbicacion(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UbicacionGrpc.Empty ActualizarUbicacion(global::UbicacionGrpc.Ubicacion request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ActualizarUbicacion, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UbicacionGrpc.Empty> ActualizarUbicacionAsync(global::UbicacionGrpc.Ubicacion request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ActualizarUbicacionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UbicacionGrpc.Empty> ActualizarUbicacionAsync(global::UbicacionGrpc.Ubicacion request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ActualizarUbicacion, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UbicacionGrpc.AdopcionesCercanas ObtenerAdopcionesCercanas(global::UbicacionGrpc.Ubicacion request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ObtenerAdopcionesCercanas(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UbicacionGrpc.AdopcionesCercanas ObtenerAdopcionesCercanas(global::UbicacionGrpc.Ubicacion request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ObtenerAdopcionesCercanas, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UbicacionGrpc.AdopcionesCercanas> ObtenerAdopcionesCercanasAsync(global::UbicacionGrpc.Ubicacion request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ObtenerAdopcionesCercanasAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UbicacionGrpc.AdopcionesCercanas> ObtenerAdopcionesCercanasAsync(global::UbicacionGrpc.Ubicacion request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ObtenerAdopcionesCercanas, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override ServicioUbicacionClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ServicioUbicacionClient(configuration);
      }
    }

  }
}
#endregion
